### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by zongzhesun** [heshuting555/TransReID#6]
Traceback (most recent call last):
  File "D:/Project/TransReID-main/train.py", line 86, in <module>
    num_query, args.local_rank
  File "D:\Project\TransReID-main\processor\processor.py", line 58, in do_train
    score, feat = model(img, target, cam_label=target_cam, view_label=target_view )
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\TransReID-main\model\make_model.py", line 182, in forward
    global_feat = self.base(x, cam_label=cam_label, view_label=view_label)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\TransReID-main\model\backbones\vit_pytorch.py", line 407, in forward
    x = self.forward_features(x, cam_label, view_label)
  File "D:\Project\TransReID-main\model\backbones\vit_pytorch.py", line 400, in forward_features
    x = blk(x)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\TransReID-main\model\backbones\vit_pytorch.py", line 182, in forward
    x = x + self.drop_path(self.attn(self.norm1(x)))
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Project\TransReID-main\model\backbones\vit_pytorch.py", line 154, in forward
    qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
我遇到了这个error,请问是什么情况啊？

**Comment by YuzhouPeng** [comment]
想问下是怎么解决的？
